net\dontdrinkandroot\doctrineexample\entity\Article:
    type: entity
    table: Article
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        price:
            type: float
    manyToMany:
        tags:
            targetEntity: net\dontdrinkandroot\doctrineexample\entity\Tag
            inversedBy: articles
            joinTable:
                name: Article_Tag
                joinColumns:
                  articles_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  tags_id:
                    referencedColumnName: id