net\dontdrinkandroot\doctrineexample\entity\Tag:
    type: entity
    table: Tag
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    manyToMany:
        articles:
            targetEntity: net\dontdrinkandroot\doctrineexample\entity\Article
            mappedBy: tags